# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61884cedbd063ce58bc45f8d2ee6aa8d02d39a8bc71ca30469852760fad79f1df1bb61639f533946f69990635026a0060283d80ddbfa40297a5420da0843277b

test:
  secret_key_base: 658840916b116998cb54636cf5c3197396cf4d269e52c2f782db063a7bb5bbf38c305c46f864fe63c37812fdebb05914ab27a301f44d560c9f48dcf57f771da3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
